$script = <<SCRIPT
mkdir $HOME/kernel-4.15
cd $HOME/kernel-4.15
wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.15/linux-headers-4.15.0-041500_4.15.0-041500.201802011154_all.deb
wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.15/linux-headers-4.15.0-041500-generic_4.15.0-041500.201802011154_amd64.deb
wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.15/linux-image-4.15.0-041500-generic_4.15.0-041500.201802011154_amd64.deb
sudo dpkg -i *.deb
sudo apt-get update
sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
sudo add-apt-repository "deb https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") $(lsb_release -cs) stable"
sudo apt-get update && sudo apt-get install -y docker-ce=$(apt-cache madison docker-ce | grep 17.03 | head -1 | awk '{print $3}')
sudo apt-get update && sudo apt-get install -y apt-transport-https
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
sudo cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF
sudo apt-get update
sudo apt-get install -y kubelet kubeadm kubectl
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: $script

  config.vm.define "master" do |master|
  config.vm.network :forwarded_port, guest: 6443, host: 64430, host_ip: "0.0.0.0"
  config.vm.network "public_network", ip: "192.168.1.10"
    master.vm.box = "ubuntu/xenial64"
    master.vm.provision :shell, inline: "hostname master.local && reboot"
  end

  config.vm.define "worker1" do |worker1|
  config.vm.network "public_network", ip: "192.168.1.11"
  config.vm.network :forwarded_port, guest: 6443, host: 64431, host_ip: "0.0.0.0"
    worker1.vm.box = "ubuntu/xenial64"
    worker1.vm.provision :shell, inline: "hostname worker1.local && reboot"
  end

  config.vm.define "worker2" do |worker2|
  config.vm.network "private_network", ip: "10.0.2.12"
  config.vm.network :forwarded_port, guest: 6443, host: 64432, host_ip: "0.0.0.0"
    worker2.vm.box = "ubuntu/xenial64"
    worker2.vm.provision :shell, inline: "hostname worker2.local && reboot"
  end

end
